### PR TITLE
Upgraded to support twitter bootstrap 2.1.0

### PR DESCRIPTION
**Pull request by kristianmandrup**
Ported files from:

https://github.com/smt/sass-twitter-bootstrap/tree/v2.1.0-bump

Cheers!

### CODE REVIEW

**Comment by addyosmani** [comment]
If it's possible to get this merged that would be so awesome.

Thanks once again for the super quick turnaround @kristianmandrup!

**Comment by sindresorhus** [comment]
me2 ^

**Comment by dfross** [comment]
+1

**Comment by paulirish** [comment]
Nice one. :metal:

**Comment by kristianmandrup** [comment]
Would be nice if someone took the 2.1 SCSS, converted it to SASS using the guidelines (a few search&replace I assume) and then copy over the 2.04 SASS files :)

I think that would allow the pull to be merged in.

**Comment by kristianmandrup** [comment]
The only problem is I've got quite a few .scss partials that I need to convert now. Well open up that Terminal; here's one line of bash to the rescue:

`for f in *.scss; do sass-convert -F scss -T sass $f ${f%%.*}.sass; done`

From:  http://ericdfields.com/2012/02/01/bash-convert-scss-or-css-to-sass/

**Comment by kristianmandrup** [comment]
Used this console bash script to convert the scss changes to sass and overwrite old 2.0.4 sass files. Latest HEAD in pull should contain these modifications. Also added note on how to do this in README for future updates!
Cheers!

**Comment by ethern8** [comment]
I downloaded, built, and installed the gem locally.  Thank you for your efforts on this.  Everything looks good, except I noticed an issue with the _mixins for the fluid grid.  It appears as though the offset is being added to the spans(n), ~ line 559.

``` Ruby
@while $i > 0
      .span#{$i}
        +fluid-span($i, $columnWidth, $gutterWidth)
        +fluid-offset($i, $columnWidth, $gutterWidth)
      $i: $i - 1
```

My knowledge of ruby is nill, so I might be completely wrong.  When I compile the SCSS to CSS the fluid grid spans are all wonky because of the added offsets.

Again, thanks for your efforts.  I am looking forward to the leveraging the latest bootstrap with Compass!

**Comment by kristianmandrup** [comment]
I took the scss straight from another repo. Never tested it myselxb

**Comment by janfoeh** [comment]
Just a quick heads up: if you get syntax errors such as

```
sass::syntaxerror: invalid css after "...ia (max-width: ": expected expression (e.g. 1px, bold), was "$navbarcollapse..." 
```

in responsive-navbar.scss, you need to update SASS to ~> 3.2.

**Comment by sindresorhus** [comment]
@vwall ping

**Comment by wyuenho** [comment]
Ahh this merge brought back the mixin conflicts with compass again. @vwall or @kristianmandrup do you guys mind prefixing all the bootstrap mixins and all references to them with "bootstrap-" ?

**Comment by kristianmandrup** [comment]
Got no time at the moment. Could it be done as a search and replace, or is it a manual task?

**Pull request merged**
