### PR TITLE
Use correct location for icon sprite image assets

### PR DESCRIPTION
**Pull request by colvint**
Could be wrong, but seems like these are the correct asset locations. Worked for me. Merge if good.

Thanks for this gem :)
- Taurus

### CODE REVIEW

**Comment by vincentp** [comment]
Same problem for me, thanks for the fix :)

**Comment by assimovt** [comment]
+1

**Comment by wyuenho** [comment]
Whoops sorry! I introduced that regression in my last big bang update to 2.0.3. I think for now you can just override this variable before you import compass-twitter-bootstrap like so:

``` sass
  $iconSpritePath: "glyphicons-halflings.png";
  $iconWhiteSpritePath: "glyphicons-halflings-white.png";

  @import "compass_twitter_bootstrap";
```

**Comment by colvint** [comment]
Using a fork for now. Thanks again for the gem :)

**Comment by wyuenho** [comment]
I take no credit for this project. Thank @vwall for this best Bootstrap port to Compass to date.

**Comment by thetizzo** [comment]
This issue seems to have been fixed.  Thanks for the PR!

**Pull request closed without merging**
