### PR TITLE
FontAwesome icon upgrade to 2.0

### PR DESCRIPTION
**Pull request by toao**
Upgraded the font-files and the .icon-css-classes to support the 70 new icons from fontawesome 2.0
Mainly copied the data from the main fontawesome repo. Left out the ie7 css-files for the moment.

### CODE REVIEW

**Comment by matenia** [comment]
+1 for this and thanks.
/me cherry-picks you!

**Comment by dfross** [comment]
+1

**Comment by patrickberkeley** [comment]
:+1:

**Comment by cyrill62** [comment]
+1

**Comment by sethladd** [comment]
+1

**Comment by requnix** [comment]
+1

**Comment by allenwei** [comment]
+1000

**Comment by marcusg** [comment]
+1

**Comment by vr-pair** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by patrickberkeley** [comment]
@vwall are you still maintaining this?

**Comment by kiwidrew** [comment]
+1, why hasn't this been merged in yet?

**Comment by kristianmandrup** [comment]
Hmm, yeah... why have the font-awesome in this repo. Not really related I would think? 
Would make more sense to make a separate `fontawesome-rails` gem, no?

**Comment by kiwidrew** [comment]
@kristianmandrup I didn't mean #67....  like the others here, I love that Font Awesome comes bundled and ready-to-go (no dependency hell!).  I just want to know why this pull request is in limbo -- @vwall, are you planning to merge or close it?

**Comment by kristianmandrup** [comment]
Well, if anyone wants a decoupled version of font-awesome 2.0, here is a new gem I just created: https://github.com/kristianmandrup/font_awesome-sass-rails

Needs testing in the wild... but at least it is 2.0 (taken from Font-Awesome-More) and should be ready to go.

PS: Discovered there was also a https://github.com/bokmann/font-awesome-rails gem, but it only comes with css

**Comment by patrickberkeley** [comment]
Awesome, @vwall. Glad to see you back.

**Pull request merged**
