### PR TITLE
Remove Font Awesome 

### PR DESCRIPTION
**Pull request by allenwei**
Font Awesome in this gem will prevent me add Font Awesome lib myself.

What about remove it from this project. So that people can add it themselves.

### CODE REVIEW

**Comment by tmaier** [comment]
About which "Font Awesome lib" are you talking? Why not updating the existing one, as proposed in #62?

**Comment by allenwei** [comment]
It's too slow to wait gem updates. 
I can not use newer Font Awesome lib because of font conflicts.
So I suggest do not include it in this gem.

**Comment by tmaier** [comment]
Well I think it fits very well to the gem. The aim of this gem is to provide twitter bootstrap and the most important components within the assets pipeline. Modified to work perfectly together with the compass gem. I'm happy this gem exists.

I would suggest to use one of the forks which are using already the latest version or create your own fork, if none of them fits your requirements.

Just see the [list of pull requests](https://github.com/vwall/compass-twitter-bootstrap/pulls). There are enough alternatives which provide the latest version of Font Awsome. If you start to use any of them, please give feedback on the pull request wether they work as expected.

**Comment by allenwei** [comment]
That what I do, I'm using my fork now.
But It's two separate libs, that means they won't update at same time. If user want to use newer version, he need fork it and remove FontAwesome like what I do.

**Comment by tmaier** [comment]
I don't get you. Don't remove Font Awsome. Update it. In your fork.

See #66: This one has the very latest Twitter Bootstrap AND Font Awsome 2.0
Or #62: An alternative update of Font Awsome 2.0

**Comment by allenwei** [comment]
ok, it's your call.
Thanks anyway

**Pull request closed without merging**
