### PR TITLE
Bootstrap 2.2.1

### PR DESCRIPTION
**Pull request by tijsverkoyen**
Upgraded the files to reflect the 2.2.1-version of Twitter Bootstrap

### CODE REVIEW

**Comment by thedjpetersen** [comment]
+1

**Comment by lanterndev** [comment]
I tried gem installing from git latest so I could benefit from bootstrap updates since the 2.0.3 release such as this one, but now I'm getting "error sass/app.sass (Line 36 of _font-awesome.scss: Undefined mixin 'ctb-font-face'.)". Is master currently not working, or is there some other way I should have installed from git? Thanks for any tips you can give.

**Comment by wyuenho** [comment]
issue #85 has the fix

Thx @tijsverkoyen for working on this and @vwall for merging! :+1:

**Comment by billsaysthis** [comment]
@vwall I may be misunderstanding something but I still see the 2.1.0 CSS (Sass) in the current master of this repo even though the JS is updated to 2.2.1.

Is it that the top level ctb Sass files didn't get their version comment updated, since I see many changed Sass files in this PR, otherwise what am I missing?

**Pull request merged**
