### PR TITLE
Upgrade Twitter Bootstrap to 2.3.1

### PR DESCRIPTION
**Pull request by szinya**
- removed `_responsive.scss` since it is not in use (`_compass_twitter_bootstrap_responsive.scss` is used instead)
- added utility classes defined in `_mixins.scss` to `_compass_twitter_bootstrap*.scss`
- reorganized the structure of `_compass_twitter_bootstrap*.scss` files to match originals
- changed the order of imports in `_buttons.scss`

### CODE REVIEW

**Comment by vwall** [comment]
Thanks!

**Comment by szinya** [comment]
You're welcome. One thing I don't get is why do we need the `stylesheets_sass` folder? I mean as far as I understand it is not used by any part of the application.

**Comment by vwall** [comment]
It's not needed at all.  Its created by the convert script to test the the SCSS creation.

**Comment by szinya** [comment]
Ok, I see. Could you please tag the new version and publish it at rubygems.org? Thanks.

**Comment by vwall** [comment]
Yes!  I'm out of town till friday but I'll do it once I'm back.  And again, thanks for the help.

**Pull request merged**
